apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2023-11-21T12:47:14Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  name: v1.apps
  uid: cd8e0978-8583-4638-a5b4-4f1ac9986889
spec:
  group: apps
  groupPriorityMinimum: 17800
  version: v1
  versionPriority: 15
status:
  conditions:
  - lastTransitionTime: "2023-11-21T12:47:14Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
