apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2023-11-21T12:47:18Z"
  name: kubeadm:get-nodes
  uid: 305e69dc-f1a0-4a81-be78-278ef5d53d18
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
