apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-11-21T12:47:16Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:endpointslicemirroring-controller
  uid: d310f246-bfbd-47b0-9dfd-479decff90c7
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:endpointslicemirroring-controller
subjects:
- kind: ServiceAccount
  name: endpointslicemirroring-controller
  namespace: kube-system
