apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"name":"configmap-list-binding"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"configmap-list-role"},"subjects":[{"kind":"ServiceAccount","name":"quiztestcc-controller-manager","namespace":"quiztestcc-system"}]}
  creationTimestamp: "2023-11-29T17:23:35Z"
  name: configmap-list-binding
  uid: 94672c2e-fbd3-4b30-96e1-9f73dc1129e6
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: configmap-list-role
subjects:
- kind: ServiceAccount
  name: quiztestcc-controller-manager
  namespace: quiztestcc-system
