apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"labels":{"app":"katafygio","chart":"katafygio-0.5.1","heritage":"Helm","release":"katafygio"},"name":"katafygio"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"katafygio"},"subjects":[{"kind":"ServiceAccount","name":"katafygio","namespace":"default"}]}
  creationTimestamp: "2024-01-03T06:08:43Z"
  labels:
    app: katafygio
    chart: katafygio-0.5.1
    heritage: Helm
    release: katafygio
  name: katafygio
  uid: e978fbd0-cea3-43b4-9500-a1a6afb4de4e
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: katafygio
subjects:
- kind: ServiceAccount
  name: katafygio
  namespace: default
