apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-11-21T12:47:16Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:ttl-after-finished-controller
  uid: 20a0da43-6131-44c0-b2f0-e451eacce579
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:ttl-after-finished-controller
subjects:
- kind: ServiceAccount
  name: ttl-after-finished-controller
  namespace: kube-system
