apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"example-webhook"},"rules":[{"apiGroups":[""],"resources":["*"],"verbs":["*"]}]}
  creationTimestamp: "2023-11-21T12:59:11Z"
  name: example-webhook
  uid: d0859fac-17a4-4c5e-85fe-9896ccb5a22b
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - '*'
