apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-11-21T12:47:16Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:root-ca-cert-publisher
  uid: b4ed6b03-311c-4fb1-9126-55ea2658e84a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:root-ca-cert-publisher
subjects:
- kind: ServiceAccount
  name: root-ca-cert-publisher
  namespace: kube-system
