apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-11-21T12:47:16Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:namespace-controller
  uid: b4321ba7-ec41-4be8-86ba-3ddf2aef2684
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:namespace-controller
subjects:
- kind: ServiceAccount
  name: namespace-controller
  namespace: kube-system
