apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-11-21T12:47:16Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:node-controller
  uid: be3781f4-f4f9-49f5-9e6b-a84384fafd26
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:node-controller
subjects:
- kind: ServiceAccount
  name: node-controller
  namespace: kube-system
