apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2024-01-02T17:25:48Z"
deprecatedLastTimestamp: "2024-01-02T17:25:48Z"
deprecatedSource:
  component: kubelet
  host: minikube
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-02T17:25:48Z"
  name: calico-kube-controllers-85578c44bf-cm6kg.17a697bd48ec5cc4
  namespace: kube-system
  uid: b137fa53-e964-4d49-bf99-b6e09a2cfe56
note: Pod sandbox changed, it will be killed and re-created.
reason: SandboxChanged
regarding:
  apiVersion: v1
  kind: Pod
  name: calico-kube-controllers-85578c44bf-cm6kg
  namespace: kube-system
  resourceVersion: "1172080"
  uid: 0f1654c2-63ea-4a9b-8947-f6e947666153
type: Normal
