apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2024-01-02T17:25:53Z"
deprecatedLastTimestamp: "2024-01-02T17:25:53Z"
deprecatedSource:
  component: kubelet
  host: minikube
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-02T17:25:53Z"
  name: calico-node-tdncx.17a697be87e0674e
  namespace: kube-system
  uid: 46aab897-22e2-400b-a6d1-ceabcf52f876
note: Container image "docker.io/calico/node:v3.26.1" already present on machine
reason: Pulled
regarding:
  apiVersion: v1
  fieldPath: spec.initContainers{mount-bpffs}
  kind: Pod
  name: calico-node-tdncx
  namespace: kube-system
  resourceVersion: "1172043"
  uid: 5f40c6a5-9fb4-4214-ace2-2e8e84832da4
type: Normal
