apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2024-01-02T17:25:44Z"
deprecatedLastTimestamp: "2024-01-02T17:25:44Z"
deprecatedSource:
  component: kubelet
  host: minikube
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-02T17:25:48Z"
  name: kube-controller-manager-minikube.17a697bc61e3e392
  namespace: kube-system
  uid: 2b65a8ab-4584-4910-acb2-e096483b80f9
note: Pod sandbox changed, it will be killed and re-created.
reason: SandboxChanged
regarding:
  apiVersion: v1
  kind: Pod
  name: kube-controller-manager-minikube
  namespace: kube-system
  uid: b3702ceb912504d37098b922ccdcfa41
type: Normal
