apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2024-01-02T17:25:50Z"
deprecatedLastTimestamp: "2024-01-02T17:25:50Z"
deprecatedSource:
  component: kubelet
  host: minikube
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-02T17:25:50Z"
  name: calico-node-tdncx.17a697bdb587da21
  namespace: kube-system
  uid: 14aa37a4-642f-41b8-84e4-c65129f25c35
note: Started container upgrade-ipam
reason: Started
regarding:
  apiVersion: v1
  fieldPath: spec.initContainers{upgrade-ipam}
  kind: Pod
  name: calico-node-tdncx
  namespace: kube-system
  resourceVersion: "1172043"
  uid: 5f40c6a5-9fb4-4214-ace2-2e8e84832da4
type: Normal
