apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2024-01-02T17:26:00Z"
deprecatedLastTimestamp: "2024-01-02T17:26:00Z"
deprecatedSource:
  component: node-controller
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-02T17:26:00Z"
  name: minikube.17a697c02ba1e745
  namespace: default
  uid: 6ba56b7b-d0de-453b-9b0b-10b839004b8f
note: 'Node minikube event: Registered Node minikube in Controller'
reason: RegisteredNode
regarding:
  apiVersion: v1
  kind: Node
  name: minikube
  uid: 7430868f-dbf0-4399-916e-ec5f730ad7fc
type: Normal
