apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2024-01-03T06:07:25Z"
deprecatedLastTimestamp: "2024-01-03T06:07:25Z"
deprecatedSource:
  component: kubelet
  host: minikube
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-03T06:07:25Z"
  name: katafygio-69d46c7d75-pfrvv.17a6c14d18c6bb82
  namespace: default
  uid: a2d34102-ce08-4f82-8a94-c9df12640e7b
note: Stopping container katafygio
reason: Killing
regarding:
  apiVersion: v1
  fieldPath: spec.containers{katafygio}
  kind: Pod
  name: katafygio-69d46c7d75-pfrvv
  namespace: default
  resourceVersion: "370676"
  uid: 49ff0fd6-ddb2-4764-949e-61f07f31bf92
type: Normal
