apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2024-01-02T17:25:44Z"
deprecatedLastTimestamp: "2024-01-02T17:25:44Z"
deprecatedSource:
  component: kubelet
  host: minikube
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-02T17:25:48Z"
  name: kube-apiserver-minikube.17a697bc687aec6e
  namespace: kube-system
  uid: b10979ca-9d36-4175-b4cf-1b4e5f7a0b66
note: Created container kube-apiserver
reason: Created
regarding:
  apiVersion: v1
  fieldPath: spec.containers{kube-apiserver}
  kind: Pod
  name: kube-apiserver-minikube
  namespace: kube-system
  uid: f241819aff4d77a34fc71bea1fac9af8
type: Normal
