apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2024-01-03T06:08:54Z"
deprecatedLastTimestamp: "2024-01-03T06:08:54Z"
deprecatedSource:
  component: kubelet
  host: minikube
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-03T06:08:54Z"
  name: katafygio-797fbcd6bf-8d6w4.17a6c161a3c8e401
  namespace: default
  uid: 3fe99900-3d1c-446b-81e4-a3b736544066
note: Created container katafygio
reason: Created
regarding:
  apiVersion: v1
  fieldPath: spec.containers{katafygio}
  kind: Pod
  name: katafygio-797fbcd6bf-8d6w4
  namespace: default
  resourceVersion: "488188"
  uid: 8381d691-6a68-4669-b63e-252036c9a84e
type: Normal
