apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2024-01-02T17:25:49Z"
deprecatedLastTimestamp: "2024-01-02T17:25:49Z"
deprecatedSource:
  component: kubelet
  host: minikube
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-02T17:25:49Z"
  name: kube-proxy-ffgxk.17a697bd83e00c49
  namespace: kube-system
  uid: b7f5e219-041d-4a6c-b9b5-bebd94d4ddf5
note: Created container kube-proxy
reason: Created
regarding:
  apiVersion: v1
  fieldPath: spec.containers{kube-proxy}
  kind: Pod
  name: kube-proxy-ffgxk
  namespace: kube-system
  resourceVersion: "1171927"
  uid: 70b17335-bdf5-41fd-aa8f-9ac210c05a1c
type: Normal
