apiVersion: events.k8s.io/v1
deprecatedCount: 5
deprecatedFirstTimestamp: "2024-01-02T17:25:58Z"
deprecatedLastTimestamp: "2024-01-02T17:26:18Z"
deprecatedSource:
  component: kubelet
  host: minikube
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-02T17:25:58Z"
  name: cert-manager-webhook-5655dcfb4b-w5mn2.17a697bfadd693d6
  namespace: cert-manager
  uid: 5a0c08c9-8597-447b-b0d9-fd351250e95b
note: 'Readiness probe failed: Get "http://10.244.0.121:6080/healthz": dial tcp 10.244.0.121:6080:
  connect: connection refused'
reason: Unhealthy
regarding:
  apiVersion: v1
  fieldPath: spec.containers{cert-manager-webhook}
  kind: Pod
  name: cert-manager-webhook-5655dcfb4b-w5mn2
  namespace: cert-manager
  resourceVersion: "1172240"
  uid: ddcad1b0-18e1-484a-bedb-cf9abdfc5b90
type: Warning
