apiVersion: flowcontrol.apiserver.k8s.io/v1beta2
kind: FlowSchema
metadata:
  annotations:
    apf.kubernetes.io/autoupdate-spec: "true"
  creationTimestamp: "2023-11-21T12:47:15Z"
  name: endpoint-controller
  uid: 673281dc-a738-4b41-bada-20c83404351e
spec:
  distinguisherMethod:
    type: ByUser
  matchingPrecedence: 150
  priorityLevelConfiguration:
    name: workload-high
  rules:
  - resourceRules:
    - apiGroups:
      - ""
      namespaces:
      - '*'
      resources:
      - endpoints
      verbs:
      - get
      - create
      - update
    subjects:
    - kind: User
      user:
        name: system:kube-controller-manager
    - kind: ServiceAccount
      serviceAccount:
        name: endpoint-controller
        namespace: kube-system
    - kind: ServiceAccount
      serviceAccount:
        name: endpointslicemirroring-controller
        namespace: kube-system
status:
  conditions:
  - lastTransitionTime: "2023-11-21T12:47:15Z"
    message: This FlowSchema references the PriorityLevelConfiguration object named
      "workload-high" and it exists
    reason: Found
    status: "False"
    type: Dangling
