apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2023-11-21T12:47:14Z"
  labels:
    kubernetes.io/metadata.name: kube-system
  name: kube-system
  uid: 97876a03-05d2-4cbb-8623-6e98cc908739
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
