apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2023-11-21T12:47:15Z"
  labels:
    kubernetes.io/metadata.name: default
  name: default
  uid: 6dba6ca2-c024-4eee-b84c-a035c5e1eb01
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
