apiVersion: flowcontrol.apiserver.k8s.io/v1beta2
kind: PriorityLevelConfiguration
metadata:
  annotations:
    apf.kubernetes.io/autoupdate-spec: "true"
  creationTimestamp: "2023-11-21T12:47:15Z"
  name: exempt
  uid: b5029ef0-6bfa-4219-8f8b-50083d9dcb05
spec:
  type: Exempt
status: {}
