apiVersion: flowcontrol.apiserver.k8s.io/v1beta2
kind: PriorityLevelConfiguration
metadata:
  annotations:
    apf.kubernetes.io/autoupdate-spec: "true"
  creationTimestamp: "2023-11-21T12:47:15Z"
  name: catch-all
  uid: cbcaaa50-4246-484b-9ecf-c15669c084bc
spec:
  limited:
    assuredConcurrencyShares: 5
    lendablePercent: 0
    limitResponse:
      type: Reject
  type: Limited
status: {}
