apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2023-11-21T12:47:17Z"
  name: kubeadm:nodes-kubeadm-config
  namespace: kube-system
  uid: 3efe9b73-ab70-4d87-86f7-7b32658eede4
rules:
- apiGroups:
  - ""
  resourceNames:
  - kubeadm-config
  resources:
  - configmaps
  verbs:
  - get
