apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2023-11-21T12:47:17Z"
  name: kubeadm:kubelet-config
  namespace: kube-system
  uid: b802bd8a-a3ef-4226-ad81-8bb3c42a86dc
rules:
- apiGroups:
  - ""
  resourceNames:
  - kubelet-config
  resources:
  - configmaps
  verbs:
  - get
