apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2023-11-21T12:47:18Z"
  name: kube-proxy
  namespace: kube-system
  uid: bc58994e-c952-4c26-831d-1b1a1134ff8f
rules:
- apiGroups:
  - ""
  resourceNames:
  - kube-proxy
  resources:
  - configmaps
  verbs:
  - get
