apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"example-webhook","namespace":"default"},"spec":{"ports":[{"name":"application","port":443,"targetPort":8443},{"name":"metrics","port":80,"targetPort":"metrics"}],"selector":{"app":"example-webhook"}}}
  creationTimestamp: "2023-12-11T11:45:45Z"
  name: example-webhook
  namespace: default
  uid: cc98c056-bf20-4224-8fd2-d1915a38a109
spec:
  clusterIP: 10.107.28.194
  clusterIPs:
  - 10.107.28.194
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: application
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: metrics
    port: 80
    protocol: TCP
    targetPort: metrics
  selector:
    app: example-webhook
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
