apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"nginx","example-webhook-enabled":"true"},"name":"nginx-service","namespace":"default"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"nginx"}}}
  creationTimestamp: "2023-11-29T03:55:02Z"
  labels:
    Operation: CREATE
    app: nginx
    author: minikube-user
    example-webhook-enabled: "true"
  name: nginx-service
  namespace: default
  uid: 8ef4a7fd-10d1-49b4-b4b0-9d8ea8ccfc4c
spec:
  clusterIP: 10.111.238.158
  clusterIPs:
  - 10.111.238.158
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
